### ISSUE TITLE
How do you create tray window and center it?

### ISSUE THREAD

**Issue by joshpetit** [kolbusa/stalonetray#13]
Is there a way to create a stalone tray of window type normal and center it on the screen? for instance using this command and having the window appear int he middle of the screen:

`stalonetray --window-type normal -t --icon-size 100`

**Comment by kolbusa** [comment]
Apologies for a late response. As far as I know, there is no way to do this using the standard geometry syntax that staonetray supports. See https://en.wikibooks.org/wiki/Guide_to_X11/Starting_Programs#Specifying_window_geometry.

**Comment by joshpetit** [comment]
Ok thanks for the update!
