### ISSUE TITLE
Icon for Double Commander in tray is very small

### ISSUE THREAD

**Issue by NailGit** [kolbusa/stalonetray#17]
The question is - where does stalonetray take icons? Icons for all programs in the tray have normal sizes but Double Commander has very small.  My config is
`decorations none
dockapp_mode simple
geometry 6x3+0-0
icon_size 32
slot_size 40
kludges force_icons_size
max_geometry 6x3
parent_bg true
transparent false
icon_gravity SE
grow_gravity SE
no_shrink true`
The OS is FVWM based on Linix Mint 20.

**Comment by kolbusa** [comment]
Applications provide their own icons. To be precise, applications provide their own windows, inside which they can do whatever they want. To investigate this further, I need more information (see bug template).

**Comment by NailGit** [comment]
What kind of information do you need? I can not find the bug template.

**Comment by kolbusa** [comment]
See this: https://github.com/kolbusa/stalonetray/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by NailGit** [comment]
There is no, in fact, an error. The icon appears in the tray, but the size is small. 
Use WM FOO (describe configuration if relevant) -- FVWM (based in Linux MInt Mate)
Launch app X -- launched Double Commander
See error -- there is no error 
The output with --log-level trace is very  long but there is no info about Double Commander. 
![stalonetray](https://user-images.githubusercontent.com/16674050/197409292-aadba345-b31f-4de7-9f85-d7aaa5dfd4b7.png)

**Comment by NailGit** [comment]
I found that this problem appears on my computer with FullHD display, only.

**Comment by kolbusa** [comment]
Seems like an application issue. Closing.
