### ISSUE TITLE
Update arch-package to use this repo as new upstream

### ISSUE THREAD

**Issue by astier** [kolbusa/stalonetray#2]
Arch Linux has a package for stalonetray in its official repository.
https://archlinux.org/packages/community/x86_64/stalonetray/

However, the upstream is still:
http://stalonetray.sourceforge.net/

I think it should be update to this new GitHub-repo. Are you the maintainer of the arch-package or should I write the maintainer a mail and ask him to update it?

**Comment by kolbusa** [comment]
I do not maintain any packages (even though I'm listed as a co-maintainer for Debian). Can you please notify the maintainer? I can make a release tag (0.8.4) if that is necessary.

**Comment by astier** [comment]
I wrote them. A new release with the updated config-file path would be great.

**Comment by kolbusa** [comment]
There you go: https://github.com/kolbusa/stalonetray/releases/tag/v0.8.4.

Feel free to close if you think this one is resolved.
