### ISSUE TITLE
Changing the icon spacing/padding?

### ISSUE THREAD

**Issue by UnnatShaneshwar** [kolbusa/stalonetray#8]

**Comment by kolbusa** [comment]
Not sure I fully understand the question. Care to elaborate? Currently stalonetray does not allow adding extra space around an icon. It should not be too hard to do, though.

**Comment by sebasijan** [comment]
This would be great

**Comment by sebasijan** [comment]
actually I just got mine to look like this, but not sure how exactly these numbers work

![image](https://user-images.githubusercontent.com/13226838/147977529-fd44db12-c0d2-435e-9407-336a1e26de2d.png)


**.stalonetrayrc** :

    icon_size 10
    slot_size 15

**Comment by WarpedSavior** [comment]
Correct me if I'm missing something obvious, but couldn't you already do this by setting e.g an "icon_size" of 16 and a slightly bigger "slot_size" (for example 20)?
