### ISSUE TITLE
Could you tell me how to use remote control?

### ISSUE THREAD

**Issue by CicadaSeventeen** [kolbusa/stalonetray#9]
I try for some time and fail to understand it. Maybe you can give me an example.

**Comment by kolbusa** [comment]
Apologies for the delay. I tried digging through my email archive at the time that this feature was added, and I did not find much. I think the remote control is to enable keyboard-only interaction with tray icons: you can add a WM-level hotkey that would execute stalonetray remote click on a certain window inside the tray. I have never personally used this, so my experience is rather limited.

**Comment by kolbusa** [comment]
As far as an example goes, it should be something like this
```sh
stalonetray --remote-click-icon "Something"
```
where `"Something"` is window name of an icon. This can be found by running `xwininfo -root -tree` and looking at the children windows of the stalonetray window.

However, there is a big caveat: most modern gui toolkits seem to filter-out synthetic events. There is a way to simulate user input via the `XTest` X11 extension, but I do not see much demand for such a feature. See https://stackoverflow.com/questions/42013047/difference-between-xtestfakebuttonevent-xsendevent for a discussion.
